### ISSUE TITLE
@pandacss/no-invalid-token-paths

### ISSUE THREAD

**Issue by RickyRoller** [chakra-ui/eslint-plugin-panda#187]
```
22:46  Error: `
    grid-template-columns: auto 380px;
    grid-auto-rows: min-content;
    grid-template-rows: unset;
  ` is an invalid token path.  @pandacss/no-invalid-token-paths
```

When using template literal syntax, the eslint plugin causes issues with thinking `grid-template-columns` is a token path. Not sure why when it's not inside `{token}` or `token(token-here)`

```
const Row = styled('div')`
  display: grid;
  gap: inherit;
  grid-template-columns: 1fr;
  grid-template-rows: min-content 500px;

  @media (min-width: token(breakpoints.md)) {
    grid-template-columns: auto 380px;
    grid-auto-rows: min-content;
    grid-template-rows: unset;
  }

  @media (min-width: token(breakpoints.lg)) {
    grid-template-columns: auto 450px;
  }
`
```

Here is a repo with the issue
https://github.com/RickyRoller/panda-css-next-js-app/blob/main/src/app/page.tsx#L16

**Comment by anubra266** [comment]
I see the issue @RickyRoller, we try to detect `{}` so it's seeing the braces of your media query as a token.
