### ISSUE TITLE
no-hardcoded-color does not support new token/opacity syntax.

### ISSUE THREAD

**Issue by MeanBoyCousin** [chakra-ui/eslint-plugin-panda#31]
Given a style such as `bgColor: 'green.30/10'`, I would expect this to be considered valid when using the `@pandacss/no-hardcoded-color` rule. Currently, linting yields `Error: "green.30/10" is not a valid color token.`

Perhaps this could be added to the rule, or considered as a possible configuration for the rule.

**Comment by MeanBoyCousin** [comment]
Why was this closed with no response?

**Comment by anubra266** [comment]
@MeanBoyCousin This was closed as completed in https://github.com/chakra-ui/eslint-plugin-panda/commit/36414a9f712c6b8a1c1ae3f773fa30447d848f90

**Comment by MeanBoyCousin** [comment]
Ahh amazing, thank you.,
