### ISSUE TITLE
`no-dynamic-styling` rule should ignore the React `key` prop

### ISSUE THREAD

**Issue by Belco90** [chakra-ui/eslint-plugin-panda#40]
### Plugin version
v0.1.0

### Bug description
The rule `no-dynamic-styling` is reporting the error “Remove dynamic value. Prefer static styles” when passing a dynamic value to [the React special `key` prop](https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key).

### Steps to reproduce
Just pass a variable to any React `key` prop:
![CleanShot 2024-03-05 at 14 23 04](https://github.com/chakra-ui/eslint-plugin-panda/assets/2677072/20ee19a3-c9c3-44fc-bae0-6912783db974)

### Expected behavior
This special React prop is not reported by the `no-dynamic-styling` rule.

### Would you like to contribute with a Pull Request?
Yes!

**Comment by anubra266** [comment]
Fixed in 28b3dfc
