### ISSUE TITLE
`no-unsafe-token-fn-usage` should maybe be ignored when used in CSS variables

### ISSUE THREAD

**Issue by bzin** [chakra-ui/eslint-plugin-panda#68]
When using a token in a CSS variable inside a `cva`, I get a `no-unsafe-token-fn-usage` warning, but when using it without, the CSS it outputs is incorrect. Do you have any recommendations to address these cases?

I see that Panda CSS could, _a priori_, detect the property that this variable would be used, and do a check if a token exists, which would make sense, or you simply would not trigger this as an incorrect `token` usage.

![CleanShot 2024-04-30 at 11 14 04](https://github.com/chakra-ui/eslint-plugin-panda/assets/382735/a9177de6-4a73-4864-8afe-99051304b47f)

**Comment by bzin** [comment]
Hi @anubra266, first of all, thank you for looking into this. However, if your current commit and PR were meant to fix this, I am still having the issue after your fix, even after updating to 0.1.2.

**Comment by anubra266** [comment]
Hi @bzin could you send a small repro. Thanks

**Comment by bzin** [comment]
I not sure why but without the `token` it works but not sure if this is intentional to work like this:

![CleanShot 2024-05-03 at 23 11 17@2x](https://github.com/chakra-ui/eslint-plugin-panda/assets/382735/5edb678e-3383-470f-9fd3-b575c40223b9)

I was expecting to need to use `token(token.key)` or `{token.key}`.

**Comment by anubra266** [comment]
Oh yeah @bzin you can use full token paths for css variables
