### ISSUE TITLE
[bug] running with extends recommended deletes my PandaCSS code.

### ISSUE THREAD

**Issue by FranciscoKloganB** [chakra-ui/eslint-plugin-panda#7]
# Description

## System

- Node v20.9.0
- PNPM 8.50
- Ubuntu 22.04

### Development Dependencies

```package.json
"devDependencies": {
    "@pandacss/dev": "^0.11.1",
    "@pandacss/eslint-plugin": "^0.0.4",
}
```

### Eslint Configuration

```js
module.exports = {
  root: true,
  env: {
    browser: true,
    es2024: true,
    node: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@pandacss/recommended', // 👈👈👈👈👈👈
    'plugin:react/recommended',
    'plugin:react-hooks/recommended',
    'prettier', // must be the penultimate plugin extension
    'plugin:prettier/recommended',
  ],
  ...moreStuffNotRelatedWithPanda
}
```

### Screenshots

![image](https://github.com/chakra-ui/eslint-plugin-panda/assets/25959244/79494802-8e40-4bdb-955a-4cf066cf416b)

**Comment by anubra266** [comment]
@FranciscoKloganB I think this file is covered by the `include` option of your config. Config related files should not be covered there.

**Comment by FranciscoKloganB** [comment]
Removing `'./themes/panda/**/*.{js,jsx,ts,tsx}'` this entry does prevent the code from being deleted. But two questions.

**Q1:** Will PandaCSS still hot reload/codegen changes from `themes/panda`? Will I need to restart the server everytime? Or what's the solution?

**Q2:** If this was wrong, shouldn't the linter throw an error at me instead of deleting my code?

**Comment by anubra266** [comment]
@FranciscoKloganB I'm not sure I understand q1.

q2: Generally, the linter can't just auto delete your code. Your code being deleter means you're running `eslint --fix` somewhere.

As for q3 and q4, you're right, we need to review the properties that are being tracked.

**Comment by FranciscoKloganB** [comment]
Regarding Q1. For some reason, I annotated that particular line in my `panda.config.ts` as a being important for hot reloading. I am not sure if I read that somewhere. So my question is, assume, my `react` project is running. Will `panda codegen` retrigger on changes within `themes/panda`, if they are no longer being tracked?

Regarding Q4 once again.

I seem to avoid the warnings like so:

```tsx
import { styled } from '@styled-system/jsx'

type MailToProps = {
  email: string
  className?: string
}

function Anchor(props) {
  return <styled.a color="tertiary" {...props} />
}

export function MailTo({ className, email }: MailToProps) {
  return (
    <Anchor
      aria-label={`Email ${email}`}
      className={className}
      href={`mailto:${email}`}
    >
      {email}
    </Anchor>
  )
}
```

**Comment by anubra266** [comment]
@FranciscoKloganB 
regarding **Q1**, I assume themes/panda are stuff imported directly/indirectly into your `panda.config`. In that case, you don't need to track them, the panda analysis on your components is different from config changes. It will work fine

For **Q2** I'll take a closer look at that

For **Q4**, I've just released a fix, that would stop panda from linting non styled prop

**Comment by anubra266** [comment]
@FranciscoKloganB I've released a fix that offers you suggestions in the editor, instead of autofixing your code in the CLI/CLI

**Comment by FranciscoKloganB** [comment]
Thank you so much for the conversation. Keep on doing great libs!
